### PR TITLE
Adds realistic user mock data instead of nameless data we have now

### PR DESCRIPTION
**Pull request by pipieter**

### CODE REVIEW

**Review by ChewingBever — COMMENTED** [review]
Why did you remove the garbage collection schedule part at the end? Don't we need those as well?

**Comment by pipieter** [comment]
> Why did you remove the garbage collection schedule part at the end? Don't we need those as well?

In a previous PR I had already redone the garbage collection schedules. On line 361-385 we add garbage collection schedules to specific schedule assignments, as is the supposed use case. The garbage collection schedules that were on line 340 and beyond were leftover mockdata that didn't serve a purpose anymore (seeing how they were out of date)

**Comment by ChewingBever** [comment]
Oh, my bad, for some reason the PR did not contain the full diff of the file, I had to look at the entire file using the file browser.

**Comment by ChewingBever** [comment]
The mockdata seems to be only scheduling students on the Kouter schedule definition, and not spread across all different  schedule definitions.

**Comment by pipieter** [comment]
I've redid the schedule assignment mock data generation. For every schedule definition on every day, there's a 50% chance for it to have a schedule assignment (I thought this was full enough to be a nice representation while still not too full). I've only added them to the _latest_ schedule definitions. I'm not sure if previous schedule definition versions should get new assignments.

**Review by ChewingBever — APPROVED** [review]

**Review by LanderDurie — APPROVED** [review]

**Pull request merged**
